使用此快速链接或手动创建标题为的文件：action-a/Dockerfile

创建一个新的分支。分支机构应有意命名，因此该分支机构的好名声可能是第一行动。
在新分支上，创建目录： 。注：如果您正在处理 GitHub.com，则可以通过命名文件同时创建目录和文件。action-aaction-a/Dockerfile
在目录中，创建一个名为 " 。action-aDockerfile
填写以下内容：Dockerfile

FROM debian:9.5-slim

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
提交您的文件

如果您在本地工作，您还需要阶段您的文件，并将分支推至 GitHub。
